version: "3.2"
services:
  php:
    build: './docker/php/'
    networks:
      - backend
    volumes:
      - ./public_html/:/var/www/html/
      - './docker/apache/demo.apache.conf:/usr/local/apache2/conf/demo.apache.conf'
  apache:
    build: './docker/apache/'
    depends_on:
      - php
    links:
      - mysql      
    networks:
      - frontend
      - backend
    ports:
      - "8080:80"
    volumes:
      - ./public_html/:/var/www/html/
  mysql:
    image: mysql:5.7
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD: 'root'
      - MYSQL_ROOT_HOST: 'mysql'
networks:
  frontend:
  backend: