version: "3.2"
services:
  php:
    build: './docker/php/'
    networks:
      - backend
    volumes:
      - ./docker/php/symfony/:/var/www/html/symfony/
      - ./docker/php/vue/:/var/www/html/vue/
      # - './docker/apache/demo.apache.conf:/usr/local/apache2/conf/demo.apache.conf'
  apache:
    build: './docker/apache/'
    depends_on:
      - php
    links:
      - mysql      
    networks:
      - frontend
      - backend
    ports:
      - "8085:80"
    volumes:
      - ./docker/php/symfony/:/var/www/html/symfony/
      - ./docker/php/vue/:/var/www/html/vue/
  mysql:
    image: mysql:5.7
    hostname: mysql
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
networks:
  frontend:
  backend: