version: "3.2"
services:
  php:
    build: './docker/php/'
    networks:
      - backend
    volumes:
      - ./public_html/:/var/www/html/
  apache:
    build: './docker/apache/'
    depends_on:
      - php
    links:
      - mysql      
    networks:
      - frontend
      - backend
    ports:
      - "8080:80"
    volumes:
      - ./public_html/:/var/www/html/
  mysql:
    image: mysql:5.6
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: 'pass'
      # MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'pass'
networks:
  frontend:
  backend: